local mods = { -- This data was copied from _retail_\...\SavedVariables\...\ClassHelper.lua
    ["Holy Paladin"] = {
        ["loadable"] = true,
        ["title"] = "Holy Paladin",
        ["unload"] = "ClassHelper.cds={\n\n}\nClassHelper.is_healer=false\nHOLY_PALADIN_MANA_BAR:Hide()\nUNLOAD()",
        ["reinit"] = "ClassHelper.cds={\n    [\"Divine Purpose\"]=false,\n    [\"Infusion of Light\"]=false\n}\nClassHelper.is_healer=true\nHOLY_PALADIN_MANA_BAR:Show()",
        ["data"] = "local timestamp,subevent,_,_,sourceName,_,_,guid,destName=CombatLogGetCurrentEventInfo()\nlocal spellId,spellName,spellSchool,amount,overkill,school,resisted,blocked,absorbed,critical,glancing,crushing,isOffHand=select(12,CombatLogGetCurrentEventInfo())\nif sourceName==UnitName(\"player\")then\n    if subevent==\"SPELL_AURA_APPLIED\"then\n        if spellName==\"Glimmer of Light\"then\n            ClassHelper:ColorPartyRaidFrame(destName,true)\n        elseif spellName==\"Infusion of Light\"then\n            if ClassHelper.cds[\"Divine Purpose\"]then\n                ClassHelper.cds[\"Divine Purpose\"]=false\n                ClassHelper.cds[\"Infusion of Light\"]=true\n            else\n                AlertSystem:ShowText(\"\\124cff00ff00Speedcast\")\n            end\n        elseif spellName==\"Hammer of Justice\"and IsInInstance()then\n            SendChatMessage(\"Hammer of Justice on \"..destName,\"YELL\")\n        elseif spellName==\"Divine Purpose\"then\n            AlertSystem:ShowText(\"\\124cffff66ffExtracast\")\n            ClassHelper.cds[\"Divine Purpose\"]=true\n            C_Timer.NewTimer(2,function()ClassHelper.cds[\"Divine Purpose\"]=false end)\n        elseif spellName==\"Divine Shield\"then\n            ClassHelper:NewBar(8,\"Divine Shield fades\")\n        elseif spellName==\"Forbearance\"then\n            ClassHelper:NewBar(30,\"Forbearance (\"..destName..\")\")\n        elseif spellName==\"Blessing of Freedom\"and destName~=UnitName(\"player\")and IsInInstance()and IsInRaid()then\n            SendChatMessage(\"Blessing of Freedom used on \"..destName..\"!\")\n        end\n    elseif subevent==\"SPELL_AURA_REMOVED\"then\n        if spellName==\"Glimmer of Light\"then\n            ClassHelper:ColorPartyRaidFrame(destName,false)\n        elseif spellName==\"Divine Purpose\"and ClassHelper.cds[\"Infusion of Light\"]then\n            AlertSystem:ShowText(\"\\124cff00ff00Speedcast\")\n            ClassHelper.cds[\"Infusion of Light\"]=false\n        elseif spellName==\"Infusion of Light\"then\n            ClassHelper.cds[\"Infusion of Light\"]=false\n        end\n    elseif subevent==\"SPELL_CAST_SUCCESS\"then\n        if spellName==\"Beacon of Virtue\"then\n            ClassHelper:NewBar(15,\"Beacon CD\",200025):RegisterEvent(0,function()AlertSystem:ShowText(\"Beacon Ready\")end)\n        elseif spellName==\"Avenging Wrath\"then\n            ClassHelper:NewBar(\"1:30\",\"Wings CD\",31884)\n        elseif spellName==\"Avenging Crusader\"then\n            ClassHelper:NewBar(\"1:30\",\"Wings CD\",216331)\n        elseif spellName==\"Aura Mastery\"and IsInInstance()then\n            SendChatMessage(\"Aura Mastery used!\")\n        end\n    end\n    ClassHelper:DoManaAlerts()\nend",
        ["load"] = "spec:Paladin Holy",
        ["init"] = "ClassHelper.cds={\n    [\"Divine Purpose\"]=false,\n    [\"Infusion of Light\"]=false\n}\nClassHelper.is_healer=true\nHOLY_PALADIN_MANA_BAR=ClassHelper:NewPowerBar(0)",
    }
}
for i,m in pairs(mods)do
    ClassHelper:CreateModFromFile(m)
end