local mods = { -- This data was copied from _retail_\...\SavedVariables\...\ClassHelper.lua
    ["Balance Druid"] = {
        ["unload"] = "BALANCE_DRUID_POWER_BAR:Hide()\nBALANCE_DRUID_MANA_BAR:Hide()\nBALANCE_DRUID_POWER_BAR:ToggleDynamicDisplay(false)\nBALANCE_DRUID_MANA_BAR:ToggleDynamicDisplay(false)\nUNLOAD()\nClassHelper.cds={\n    \n}",
        ["title"] = "Balance Druid",
        ["loadable"] = true,
        ["reinit"] = "BALANCE_DRUID_POWER_BAR:Show()\nBALANCE_DRUID_MANA_BAR:Show()\nClassHelper.cds={\n    [\"Lunar Strike\"]=false,\n    [\"Solar Wrath\"]=false,\n    [\"Regrowth\"]=false\n}",
        ["data"] = "local timestamp,subevent,_,_,sourceName,_,_,guid,destName=CombatLogGetCurrentEventInfo()\nlocal spellId,spellName,spellSchool,amount,overkill,school,resisted,blocked,absorbed,critical,glancing,crushing,isOffHand=select(12,CombatLogGetCurrentEventInfo())\nif sourceName==UnitName(\"player\")then\n    if subevent==\"SPELL_CAST_START\"then\n        if spellName==\"Regrowth\"then\n            local function update()\n                local cost=GetSpellPowerCost(\"Regrowth\")[1].cost\n                local a=UnitCastingInfo(\"player\")\n                if a and a==\"Regrowth\"then\n                    BALANCE_DRUID_MANA_BAR:ToggleDynamicDisplay(true)\n                    BALANCE_DRUID_MANA_BAR:DynamicUpdate(0-cost)\n                    C_Timer.NewTimer(0.05,update)\n                else\n                    BALANCE_DRUID_MANA_BAR:ToggleDynamicDisplay(false)\n                end\n            end\n            update()\n        elseif spellName==\"Lunar Strike\"then\n            local function update()\n                local a=UnitCastingInfo(\"player\")\n                if a and a==\"Lunar Strike\"then\n                    BALANCE_DRUID_POWER_BAR:ToggleDynamicDisplay(true)\n                    BALANCE_DRUID_POWER_BAR:DynamicUpdate(12)\n                    C_Timer.NewTimer(0.05,update)\n                else\n                    BALANCE_DRUID_POWER_BAR:ToggleDynamicDisplay(false)\n                end\n            end\n            update()\n        elseif spellName==\"Solar Wrath\"then\n            local function update()\n                local a=UnitCastingInfo(\"player\")\n                if a and a==\"Solar Wrath\"then\n                    BALANCE_DRUID_POWER_BAR:ToggleDynamicDisplay(true)\n                    BALANCE_DRUID_POWER_BAR:DynamicUpdate(8)\n                    C_Timer.NewTimer(0.05,update)\n                else\n                    BALANCE_DRUID_POWER_BAR:ToggleDynamicDisplay(false)\n                end\n            end\n            update()\n        end\n    end\nend",
        ["load"] = "spec:Druid Balance",
        ["init"] = "BALANCE_DRUID_POWER_BAR=ClassHelper:NewPowerBar(\"ASTRAL_POWER\")\n:DisplayNumber()\n:ClearFade()\n:SetColor(0,0.5,1,0.2)\n:SetDynamicColor(1,1,0,0.2)\n:Fade(1,\"LESSTHAN\",50,1,0.5,0,0.2)\n:Fade(1,\"LESSTHAN\",40,1,0,0,0.2)\nBALANCE_DRUID_MANA_BAR=ClassHelper:NewPowerBar(\"MANA\")\n:SetSize(300,32)\n:SetPoint(\"CENTER\",0,-160,UIParent)\n:SetDynamicColor(1,1,1,0.2)\nClassHelper.cds={\n    [\"START_CAST\"]=false\n}",
    }
}
for i,m in pairs(mods)do
    ClassHelper:CreateModFromFile(m)
end